---
apiVersion: batch/v1
kind: Job
metadata:
  name: simulator
  labels:
    name: simulator
spec:
  template:
    spec:
      containers:
      - name: simulator
        image: evanw1999/simulator:public
        imagePullPolicy: Always
        env: 
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONPATH
          value: "/user/home"
        resources:
          limits:
            memory: "4Gi"
            cpu: "500m"
      restartPolicy: Never
      schedulerName: kube-batch
